"""Video and Channel tables

Revision ID: 2002983e19f4
Revises: 
Create Date: 2019-12-31 13:52:02.630357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2002983e19f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=256), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_downloaded', sa.Boolean(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thumbnail_url')
    )
    op.create_index(op.f('ix_video_duration'), 'video', ['duration'], unique=False)
    op.create_index(op.f('ix_video_is_downloaded'), 'video', ['is_downloaded'], unique=False)
    op.create_index(op.f('ix_video_title'), 'video', ['title'], unique=False)
    op.create_index(op.f('ix_video_upload_date'), 'video', ['upload_date'], unique=False)
    op.create_index(op.f('ix_video_video_id'), 'video', ['video_id'], unique=True)
    op.create_index(op.f('ix_video_view_count'), 'video', ['view_count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_view_count'), table_name='video')
    op.drop_index(op.f('ix_video_video_id'), table_name='video')
    op.drop_index(op.f('ix_video_upload_date'), table_name='video')
    op.drop_index(op.f('ix_video_title'), table_name='video')
    op.drop_index(op.f('ix_video_is_downloaded'), table_name='video')
    op.drop_index(op.f('ix_video_duration'), table_name='video')
    op.drop_table('video')
    op.drop_table('channel')
    # ### end Alembic commands ###
