"""remove video_id and duration from index

Revision ID: cc7561d18c01
Revises: 2002983e19f4
Create Date: 2019-12-31 14:11:47.685082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7561d18c01'
down_revision = '2002983e19f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_duration', table_name='video')
    op.drop_index('ix_video_video_id', table_name='video')
    op.create_unique_constraint(None, 'video', ['video_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='unique')
    op.create_index('ix_video_video_id', 'video', ['video_id'], unique=1)
    op.create_index('ix_video_duration', 'video', ['duration'], unique=False)
    # ### end Alembic commands ###
